In [2]:
import xarray as xr
import numpy as np
import pandas as pd
import netCDF4
import cartopy.crs as ccrs
import matplotlib.pyplot as plt

In [3]:
data_dir = '/lus/dal/cccr_rnd/manmeet/deepsd/data/prism/ppt/raw/prism_ppt_4km2_2014.nc'
ds = xr.open_dataset(data_dir)

In [19]:
ds.ppt[:100,0,0]==np.nan

<xarray.DataArray 'ppt' (time: 100)>
array([False, False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False, False])
Coordinates:
    lon      float64 -125.0
    lat      float64 49.94
  * time     (time) datetime64[ns] 2014-01-01 2014-01-02 ... 2014-04-10

In [20]:
ds

<xarray.Dataset>
Dimensions:  (lat: 621, lon: 1405, time: 365)
Coordinates:
  * lon      (lon) float64 -125.0 -125.0 -124.9 -124.9 ... -66.6 -66.56 -66.52
  * lat      (lat) float64 49.94 49.9 49.85 49.81 ... 24.23 24.19 24.15 24.1
  * time     (time) datetime64[ns] 2014-01-01 2014-01-02 ... 2014-12-31
Data variables:
    ppt      (time, lat, lon) float32 ...

In [26]:
ds.ppt.values

array([[[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]],

       [[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]],

       [[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]],

       ...,

       [[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan

In [27]:
ds.ppt.data

array([[[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]],

       [[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]],

       [[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]],

       ...,

       [[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan

In [35]:
ds.ppt.coords

Coordinates:
  * lon      (lon) float64 -125.0 -125.0 -124.9 -124.9 ... -66.6 -66.56 -66.52
  * lat      (lat) float64 49.94 49.9 49.85 49.81 ... 24.23 24.19 24.15 24.1
  * time     (time) datetime64[ns] 2014-01-01 2014-01-02 ... 2014-12-31

In [46]:
ds.ppt.coords['lon'][0]

<xarray.DataArray 'lon' ()>
array(-125.020833)
Coordinates:
    lon      float64 -125.0

In [47]:
ds.ppt.coords['lon'][0]

<xarray.DataArray 'lon' ()>
array(-125.020833)
Coordinates:
    lon      float64 -125.0

In [40]:
ds.ppt.dims

('time', 'lat', 'lon')

In [41]:
ds.ppt.dims[0]

'time'

In [49]:
ds.time.attrs

OrderedDict()

In [50]:
ds.time

<xarray.DataArray 'time' (time: 365)>
array(['2014-01-01T00:00:00.000000000', '2014-01-02T00:00:00.000000000',
       '2014-01-03T00:00:00.000000000', ..., '2014-12-29T00:00:00.000000000',
       '2014-12-30T00:00:00.000000000', '2014-12-31T00:00:00.000000000'],
      dtype='datetime64[ns]')
Coordinates:
  * time     (time) datetime64[ns] 2014-01-01 2014-01-02 ... 2014-12-31

In [51]:
ds.info()

xarray.Dataset {
dimensions:
	lat = 621 ;
	lon = 1405 ;
	time = 365 ;

variables:
	float64 lon(lon) ;
	float64 lat(lat) ;
	float32 ppt(time, lat, lon) ;
	datetime64[ns] time(time) ;

// global attributes:
}

In [ ]:
data_dir = 'new.nc'
ds.to_netcdf(dataDIR)